### ISSUE TITLE
JRemesh: Path to Instant Meshes is missing.

### ISSUE THREAD

**Issue by jersonlatorre** [jayanam/jremesh-tools#9]
I get this error using Blender on MacOS. I put the correct path to the application "Instant Remesh" and have tried different routes thinking it was a permissions issue, but nothing has worked.

**Comment by HiddenStones0** [comment]
I have the same Issue how we can fix this ?

**Comment by domint** [comment]
You need to put the path to the binary not the app: "/Applications/Instant Meshes.app/Contents/MacOS/Instant Meshes".
You do it by manually typing the path in the top area in the browse window and then selecting "Instant Meshes"

Included a short video so it's clearer how to do it. The problem is that apps in the mac are just folders containing all the resources and the add-on needs to know where the binary is, but the browser in blender doesn't let you directly navigate to it.

Hope it helps. 


https://user-images.githubusercontent.com/870915/233836993-c8353eba-9df2-493d-90ee-1810895d6b9e.mp4

**Comment by eliecer696** [comment]
the video appears not to be working

**Comment by Manoranjan-samal** [comment]
What to do for Windows ?

**Comment by Toaster100** [comment]
> What to do for Windows ?

same here not sure what to do?

**Comment by jayanam** [comment]
For Windows you just add the path to the InstantMeshes application, like
described in the docs

**Comment by Dmitrijsmok** [comment]
I installed the app using command line in other folder, so if anybody have the same issue, you need to go to the Instant Meshes installation folder and on the right button from the Instant Meshes.app choose Show Package Contents to get to requested directory: .../instant-meshes/Instant Meshes.app/Contents/MacOS

**Comment by nimbling** [comment]
I just copied the Mac executable out of the .app bundle and put it in my blender add-ons folder. Then told jremesh where it's at. Works like a charm 🙏
